version: "3"

services:
  livekit:
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml --node-ip ${LIVEKIT_NODE_IP:-127.0.0.1}
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "30100-30400:30100-30400/udp"
      - "5349:5349"
    env_file:
      - .env
    volumes:
      - ./${LIVEKIT_CONFIG_FILE:-config.yml}:/etc/livekit.yaml:ro
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_NICE

networks: {}
