---
app_name: chatbe
app_dir: /opt/chatbe

ghcr_registry: ghcr.io
ghcr_image: ghcr.io/phuong261104/chatbe

backend_container_name: chatbe-backend-prod
backend_port: "3000"
backend_env_file: .env.production

redis_container_name: chatbe-redis-prod
redis_port: "6379"

# GitHub Secrets
ghcr_user: "{{ lookup('env', 'GITHUB_ACTOR') }}"
ghcr_token: ""  # Set via --extra-vars "ghcr_token=xxx" or Ansible vault

network_name: chatbe-network
volumes:
  uploads: chatbe-uploads
  logs: chatbe-logs
